version: '3.3'

volumes:
  postgres_data: {}

services:
  backend:
    build: ./backend
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    restart: on-failure
    env_file:
      - ./backend/.env.docker
    ports:
      - '8000:8000'


  postgres:
    image: postgres:12.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: ./backend/.env.docker


  redis:
    image: library/redis:5.0-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
